### ISSUE TITLE
Error during setup of component usps_mail  on Home Assistant 0.81.6

### ISSUE THREAD

**Issue by carlostico** [custom-components/usps_mail#4]
TypeError: load_platform() missing 2 required positional arguments: 'discovered' and 'hass_config'

**Comment by ludeeus** [comment]
Try to upgrade HA til version 0.82.0 and this component to 0.0.6

**Comment by carlostico** [comment]
I get Invalid Config :  The following components and platforms could not be set up:
usps-mail ,Please check your config.   After updating HA to 0.82.0 and component to 0.0.6

**Comment by ludeeus** [comment]
Get the debug log for this

**Comment by maykar** [comment]
Getting the same TypeError and Invalid Config here.

`
2018-11-16 11:36:36 ERROR (MainThread) [homeassistant.setup] Error during setup of component usps_mail
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/setup.py", line 148, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/usps_mail.py", line 79, in setup
    load_platform(hass, 'camera', DOMAIN)
TypeError: load_platform() missing 2 required positional arguments: 'discovered' and 'hass_config'`

Not seeing anything more of interest in debug log

**Comment by ludeeus** [comment]
Aha!
Thanks @maykar that helps alot! :D

**Comment by ludeeus** [comment]
Can one of you try to change line 79 from:
```python
load_platform(hass, 'camera', DOMAIN)
```

to:
```python
load_platform(hass, 'camera', DOMAIN, {}, config)
```

**Comment by maykar** [comment]
It looks like that might have done it. Of course I have nothing coming today, but the no mail image displays fine and I get no errors in the log.
